# Deep learning
-  The “deep” in “deep learning” isn’t a reference to any kind of deeper understanding achieved by the approach; rather, it stands for this idea of successive layers of representations. 
- Meanwhile, other approaches to machine learning tend to focus on learning only one or two layers of representations of the data (say, taking a pixel histogram and then applying a classification rule); hence, they’re sometimes called shallow learning.

- loss function
- fwd and bwd propagation
- optimizer >>> adjust weight in reverse direction (bwd propagation)
- threshold>> activation function

## Artificial Neural Networks
- using image data

### logistic regression 


In [1]:
!pip install tensorflow

In [1]:
import tensorflow

In [2]:
 from tensorflow.keras.datasets import mnist
 (train_images, train_labels), (test_images, test_labels) = mnist.load_data() #mnist list of numbers in form of image

In [3]:
train_images[0] #it is showing pixels value


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [4]:
train_images[1:3]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [5]:
train_labels[1]

0

In [6]:
from PIL import Image # python image learning called pillo 
#to see image
im=Image.fromarray(train_images[1])


In [7]:
im

In [8]:
train_images.shape  #60000 is depth or num of images 28 is x and 28 is y

(60000, 28, 28)

In [9]:
from PIL import Image # python image learning called pillo 
#to see image
km=Image.fromarray(train_images[0])
km

In [10]:
from tensorflow.keras import models 
from tensorflow.keras import layers
model = models.Sequential()
model.add(layers.Dense(512, activation="relu",input_shape=(28*28,))) #(28*28,))) 1 d array
#relu and foftmax are activation function
model.add(layers.Dense(10, activation="softmax"))#activation function =linearity to non linear
#2 layers of sequential (added vertically)
#layer 1 has 512 neurons
#layer 2 has 10 neurons

## before fitting model


In [11]:
from tensorflow.keras.utils import to_categorical #onehotencoder
test_labels_by_cat=to_categorical(test_labels)
train_labels_by_cat=to_categorical(train_labels)
train_labels_by_cat[0]
#model.compile(optimizer="rmsprop",loss="sparse_categorical_crossentropy",metrics=["accuracy"]) ab loss me sparse nhi aye ga

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

 ## before fitting model must be compiled

In [12]:
model.compile(optimizer="rmsprop",loss="sparse_categorical_crossentropy",metrics=["accuracy"]) 

model.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"]) 

## data must b e in the shape as the model require

In [13]:
train_images = train_images.reshape((60000, 784))
train_images = train_images.astype("float32") / 255 
#image k pixels ki value 255 tk he. iski data ki range choti krne k liye max se devide kr diya
#take model ka time kam lage data ko normalize kia he
#answer float me aye ga
test_images = test_images.reshape((10000, 784))
test_images = test_images.astype("float32") / 255

In [14]:
train_images[0].shape #reshaped in 1D

(784,)

## Fitting / training the model 

In [15]:
model.fit(train_images, train_labels_by_cat, epochs=5, batch_size=128) 
#batch_size = no. of sample sample +learning size >> Varbose=0,calculation display nhi hogi


Epoch 1/5


InvalidArgumentError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\Users\HP\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
      app.start()
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
      self.io_loop.start()
    File "C:\Users\HP\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
      self._run_once()
    File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
      handle._run()
    File "C:\Users\HP\anaconda3\Lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
      reply_content = await reply_content
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
      res = shell.run_cell(
    File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
      result = self._run_cell(
    File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
      result = runner(coro)
    File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\HP\AppData\Local\Temp\ipykernel_5016\3504017414.py", line 1, in <module>
      model.fit(train_images, train_labels_by_cat, epochs=5, batch_size=128)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1742, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1338, in train_function
      return step_function(self, iterator)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1322, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1303, in run_step
      outputs = model.train_step(data)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1081, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1139, in compute_loss
      return self.compiled_loss(
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\losses.py", line 2354, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "C:\Users\HP\anaconda3\Lib\site-packages\keras\src\backend.py", line 5762, in sparse_categorical_crossentropy
      res = tf.nn.sparse_softmax_cross_entropy_with_logits(
Node: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'
logits and labels must have the same first dimension, got logits shape [128,10] and labels shape [1280]
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_592]

In [ ]:
model.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"])  
#running Again without sparse

In [ ]:
model.fit(train_images, train_labels_by_cat, epochs=5, batch_size=128) 
#batch_size = no. of sample sample +learning size >> Varbose=0,calculation display nhi hogi


## labels


In [ ]:
train_labels

## model layers summery

In [ ]:
model.summary()

In [ ]:
train_images.shape #28*28 #from 3D to 2D

In [ ]:
test_digits=test_images[0:10]
pred=model.predict(test_digits)


In [ ]:
pred

In [ ]:
model.predict(test_digits[[0]])

In [ ]:
import numpy as np

In [ ]:
np.argmax(model.predict(test_digits[[0]])) #our data in 2 D

In [ ]:
test_labels[0]

In [ ]:
test_labels

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

In [ ]:
eight = Image.open('WhatsApp Image 2023-08-25 at 4.00.40 PM.jpeg') #WhatsApp Image 2023-08-25 at 4.00.40 PM= file name
eight

In [ ]:
image = eight.convert("L")

# Save the grayscale image
image.save("grayscale_eight.jpg")

In [ ]:
eight_grey = Image.open('grayscale_eight.jpg')
arr = np.asarray(eight_grey)
arr

In [ ]:
arr.shape

In [ ]:
arr784 = arr.reshape(1,784) #for convert in2D

In [ ]:
model.predict(arr784)

In [ ]:
np.argmax(model.predict(arr784))

In [ ]:
#or full code in one line
np.argmax(model.predict(np.asarray(Image.open('grayscale_eight.jpg')).reshape(1,784)))

### for image 3

In [ ]:
three = Image.open('three.jpeg') #WhatsApp Image 2023-08-25 at 4.00.40 PM= file name
three

In [ ]:
image = three.convert("L")

# Save the grayscale image
image.save("grayscale_three.jpg")

In [ ]:
#or full code in one line
np.argmax(model.predict(np.asarray(Image.open('grayscale_three.jpg')).reshape(1,784)))